development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: controle_de_ponto_development
      hosts:
        - localhost:27017
      options:
        max_pool_size: 1
        
  # Configure Mongoid specific options. (optional)
  options:

test:
  clients:
    default:
      database: controle_de_ponto_test
      hosts:
        - localhost:27017
      options:
        max_pool_size: 1

# <%= ENV['MONGODB_URL'] %>
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
